name: Build Flipper App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug — List project structure
        run: |
          echo "::group::Project structure"
          tree -L 3
          echo "::endgroup::"

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build
        with:
          sdk-channel: release

      - name: Upload FAP artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart_portail_tool.fap
          path: ${{ steps.build.outputs.fap-artifacts }}

