name: Build Flipper App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install ufbt
        run: |
          pip install ufbt

      - name: Build Flipper App
        run: |
          cd applications_user/smart_portail_tool
          ufbt

      - name: Upload FAP artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart_portail_tool.fap
          path: ${{ steps.build.outputs.fap-artifacts }}

